name: build-and-publish--biconomy-and-stackup

on:
  push:
    branches: ['main']
  # we can also trigger manually in case needed
  workflow_dispatch:
  pull_request:
    branches: ['main']
    types:
      [closed]
jobs:
  build:
    runs-on: mpc-account-abstraction-sdk-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm i
          pushd packages/mpc
          npm run test
          npm run build
          popd
          pushd packages/biconomy/nextJs
          echo "API_KEY=${{ secrets.BICONOMY_API_KEY }}" >> .env 
          npm i &&  npm run build
          popd
          pushd packages/stackup/nextJs
          echo "API_KEY=${{ secrets.STACKUP_API_KEY }}" >> .env 
          npm i &&  npm run build
          popd

      - name: Build artifact
        run: |
          /usr/bin/7z a ./biconomy-stackup.7z ./packages/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: biconomy-stackup
          path: ./biconomy-stackup.7z
          
  deploy-prod:
    runs-on: mpc-account-abstraction-sdk-stage-deployer-prod
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: biconomy-stackup
          path: ./
      - run: |
            if [ -d "/opt/service/update" ]; then rm -Rf /opt/service/update; fi 
            mkdir /opt/service/update/
            mv ./biconomy-stackup.7z /opt/service/update/
      - run: cd /opt/service/update/ && 7z x biconomy-stackup.7z
      - run: cd /opt/service/update/biconomy/nextJs && npm i 
      - run: cd /opt/service/update/stackup/nextJs && npm i 
      - run: if [ -d "/opt/service/biconomy" ]; then rm -Rf /opt/service/biconomy; fi
      - run: mv /opt/service/update/biconomy/nextJs /opt/service/biconomy
      - run: if [ -d "/opt/service/stackup" ]; then rm -Rf /opt/service/stackup; fi
      - run: mv /opt/service/update/stackup/nextJs /opt/service/stackup
      - run: sudo systemctl restart biconomy.service stackup.service

          

